[2024-09-11T01:52:13.294+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-11T01:52:13.339+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v4.seccond_task scheduled__2022-06-26T00:00:00+00:00 [queued]>
[2024-09-11T01:52:13.353+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v4.seccond_task scheduled__2022-06-26T00:00:00+00:00 [queued]>
[2024-09-11T01:52:13.354+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-09-11T01:52:13.384+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): seccond_task> on 2022-06-26 00:00:00+00:00
[2024-09-11T01:52:13.397+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4854) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-11T01:52:13.399+0000] {standard_task_runner.py:63} INFO - Started process 4865 to run task
[2024-09-11T01:52:13.397+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v4', 'seccond_task', 'scheduled__2022-06-26T00:00:00+00:00', '--job-id', '1076', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpg5tzobwi']
[2024-09-11T01:52:13.400+0000] {standard_task_runner.py:91} INFO - Job 1076: Subtask seccond_task
[2024-09-11T01:52:13.477+0000] {task_command.py:426} INFO - Running <TaskInstance: our_first_dag_v4.seccond_task scheduled__2022-06-26T00:00:00+00:00 [running]> on host 0359316e7bd1
[2024-09-11T01:52:13.657+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vohoang' AIRFLOW_CTX_DAG_ID='our_first_dag_v4' AIRFLOW_CTX_TASK_ID='seccond_task' AIRFLOW_CTX_EXECUTION_DATE='2022-06-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-06-26T00:00:00+00:00'
[2024-09-11T01:52:13.658+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-11T01:52:13.684+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-11T01:52:13.686+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "hey, I am task2 and will be running after task 1"']
[2024-09-11T01:52:13.707+0000] {subprocess.py:86} INFO - Output:
[2024-09-11T01:52:13.708+0000] {subprocess.py:93} INFO - hey, I am task2 and will be running after task 1
[2024-09-11T01:52:13.709+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-11T01:52:13.711+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-11T01:52:13.764+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v4, task_id=seccond_task, run_id=scheduled__2022-06-26T00:00:00+00:00, execution_date=20220626T000000, start_date=20240911T015213, end_date=20240911T015213
[2024-09-11T01:52:13.855+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-11T01:52:13.880+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-11T01:52:13.898+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
