[2024-09-11T01:54:36.933+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-11T01:54:36.996+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v4.third_task scheduled__2023-04-06T00:00:00+00:00 [queued]>
[2024-09-11T01:54:37.012+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v4.third_task scheduled__2023-04-06T00:00:00+00:00 [queued]>
[2024-09-11T01:54:37.013+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-09-11T01:54:37.062+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): third_task> on 2023-04-06 00:00:00+00:00
[2024-09-11T01:54:37.076+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=7696) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-11T01:54:37.077+0000] {standard_task_runner.py:63} INFO - Started process 7704 to run task
[2024-09-11T01:54:37.076+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v4', 'third_task', 'scheduled__2023-04-06T00:00:00+00:00', '--job-id', '1922', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpkg6k708x']
[2024-09-11T01:54:37.079+0000] {standard_task_runner.py:91} INFO - Job 1922: Subtask third_task
[2024-09-11T01:54:37.143+0000] {task_command.py:426} INFO - Running <TaskInstance: our_first_dag_v4.third_task scheduled__2023-04-06T00:00:00+00:00 [running]> on host 0359316e7bd1
[2024-09-11T01:54:37.275+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vohoang' AIRFLOW_CTX_DAG_ID='our_first_dag_v4' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2023-04-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-06T00:00:00+00:00'
[2024-09-11T01:54:37.277+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-11T01:54:37.297+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-11T01:54:37.298+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "hey, I am task3 and will be running after task 1"']
[2024-09-11T01:54:37.312+0000] {subprocess.py:86} INFO - Output:
[2024-09-11T01:54:37.314+0000] {subprocess.py:93} INFO - hey, I am task3 and will be running after task 1
[2024-09-11T01:54:37.315+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-11T01:54:37.315+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-11T01:54:37.355+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v4, task_id=third_task, run_id=scheduled__2023-04-06T00:00:00+00:00, execution_date=20230406T000000, start_date=20240911T015436, end_date=20240911T015437
[2024-09-11T01:54:37.415+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-11T01:54:37.426+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
