[2024-07-02T03:54:27.704+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-02T03:54:27.747+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgers_hooks_v01.postgres_to_s3 scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T03:54:27.755+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgers_hooks_v01.postgres_to_s3 scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T03:54:27.756+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 8
[2024-07-02T03:54:27.772+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2024-07-01 00:00:00+00:00
[2024-07-02T03:54:27.779+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgers_hooks_v01', 'postgres_to_s3', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgress_hook.py', '--cfg-path', '/tmp/tmpt7iev2ec']
[2024-07-02T03:54:27.781+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask postgres_to_s3
[2024-07-02T03:54:27.782+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=16511) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-02T03:54:27.783+0000] {standard_task_runner.py:63} INFO - Started process 16512 to run task
[2024-07-02T03:54:27.823+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgers_hooks_v01.postgres_to_s3 scheduled__2024-07-01T00:00:00+00:00 [running]> on host 468cd84e5e4e
[2024-07-02T03:54:27.901+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vohoang' AIRFLOW_CTX_DAG_ID='dag_with_postgers_hooks_v01' AIRFLOW_CTX_TASK_ID='postgres_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-02T03:54:27.902+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-02T03:54:27.922+0000] {base.py:84} INFO - Using connection ID 'postgres_conn_id' for task execution.
[2024-07-02T03:54:27.930+0000] {dag_with_postgress_hook.py:31} INFO - Saved orders data in text file get
[2024-07-02T03:54:27.930+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-02T03:54:27.931+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-02T03:54:27.939+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_postgers_hooks_v01, task_id=postgres_to_s3, run_id=scheduled__2024-07-01T00:00:00+00:00, execution_date=20240701T000000, start_date=20240702T035427, end_date=20240702T035427
[2024-07-02T03:54:27.956+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-02T03:54:27.971+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T03:54:27.975+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
