[2024-09-11T02:38:03.901+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-11T02:38:03.963+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2024-07-05T00:00:00+00:00 [queued]>
[2024-09-11T02:38:03.978+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2024-07-05T00:00:00+00:00 [queued]>
[2024-09-11T02:38:03.979+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-09-11T02:38:04.096+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): delete_data_from_table> on 2024-07-05 00:00:00+00:00
[2024-09-11T02:38:04.108+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=18070) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-11T02:38:04.110+0000] {standard_task_runner.py:63} INFO - Started process 18077 to run task
[2024-09-11T02:38:04.114+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'delete_data_from_table', 'scheduled__2024-07-05T00:00:00+00:00', '--job-id', '3947', '--raw', '--subdir', 'DAGS_FOLDER/13_dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp9uv5dury']
[2024-09-11T02:38:04.116+0000] {standard_task_runner.py:91} INFO - Job 3947: Subtask delete_data_from_table
[2024-09-11T02:38:04.216+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2024-07-05T00:00:00+00:00 [running]> on host 0359316e7bd1
[2024-09-11T02:38:04.395+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vohoang' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='delete_data_from_table' AIRFLOW_CTX_EXECUTION_DATE='2024-07-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-05T00:00:00+00:00'
[2024-09-11T02:38:04.396+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-11T02:38:04.423+0000] {sql.py:276} INFO - Executing: 
            delete from dag_runs where dt = '2024-07-05' and dag_id = 'dag_with_postgres_operator_v03'
        
[2024-09-11T02:38:04.436+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-09-11T02:38:04.454+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-09-11T02:38:04.482+0000] {sql.py:487} INFO - Running statement: 
            delete from dag_runs where dt = '2024-07-05' and dag_id = 'dag_with_postgres_operator_v03'
        , parameters: None
[2024-09-11T02:38:04.490+0000] {sql.py:496} INFO - Rows affected: 0
[2024-09-11T02:38:04.495+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-11T02:38:04.524+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v03, task_id=delete_data_from_table, run_id=scheduled__2024-07-05T00:00:00+00:00, execution_date=20240705T000000, start_date=20240911T023803, end_date=20240911T023804
[2024-09-11T02:38:04.613+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-11T02:38:04.631+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
