[2024-09-11T01:58:53.838+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-11T01:58:53.868+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v4.seccond_task scheduled__2024-05-18T00:00:00+00:00 [queued]>
[2024-09-11T01:58:53.883+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v4.seccond_task scheduled__2024-05-18T00:00:00+00:00 [queued]>
[2024-09-11T01:58:53.884+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-09-11T01:58:53.917+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): seccond_task> on 2024-05-18 00:00:00+00:00
[2024-09-11T01:58:53.931+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=11754) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-11T01:58:53.931+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v4', 'seccond_task', 'scheduled__2024-05-18T00:00:00+00:00', '--job-id', '3152', '--raw', '--subdir', 'DAGS_FOLDER/7. our_first_dag.py', '--cfg-path', '/tmp/tmpptgk4tie']
[2024-09-11T01:58:53.933+0000] {standard_task_runner.py:63} INFO - Started process 11788 to run task
[2024-09-11T01:58:53.934+0000] {standard_task_runner.py:91} INFO - Job 3152: Subtask seccond_task
[2024-09-11T01:58:54.006+0000] {task_command.py:426} INFO - Running <TaskInstance: our_first_dag_v4.seccond_task scheduled__2024-05-18T00:00:00+00:00 [running]> on host 0359316e7bd1
[2024-09-11T01:58:54.155+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vohoang' AIRFLOW_CTX_DAG_ID='our_first_dag_v4' AIRFLOW_CTX_TASK_ID='seccond_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-18T00:00:00+00:00'
[2024-09-11T01:58:54.156+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-11T01:58:54.158+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-11T01:58:54.159+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "hey, I am task2 and will be running after task 1"']
[2024-09-11T01:58:54.176+0000] {subprocess.py:86} INFO - Output:
[2024-09-11T01:58:54.178+0000] {subprocess.py:93} INFO - hey, I am task2 and will be running after task 1
[2024-09-11T01:58:54.179+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-11T01:58:54.180+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-11T01:58:54.214+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v4, task_id=seccond_task, run_id=scheduled__2024-05-18T00:00:00+00:00, execution_date=20240518T000000, start_date=20240911T015853, end_date=20240911T015854
[2024-09-11T01:58:54.269+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-11T01:58:54.291+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-11T01:58:54.300+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
