[2024-09-11T01:50:31.059+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-11T01:50:31.110+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v4.seccond_task scheduled__2021-12-10T00:00:00+00:00 [queued]>
[2024-09-11T01:50:31.124+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v4.seccond_task scheduled__2021-12-10T00:00:00+00:00 [queued]>
[2024-09-11T01:50:31.125+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-09-11T01:50:31.151+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): seccond_task> on 2021-12-10 00:00:00+00:00
[2024-09-11T01:50:31.163+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2723) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-11T01:50:31.170+0000] {standard_task_runner.py:63} INFO - Started process 2737 to run task
[2024-09-11T01:50:31.167+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v4', 'seccond_task', 'scheduled__2021-12-10T00:00:00+00:00', '--job-id', '407', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp4ezfo9bz']
[2024-09-11T01:50:31.177+0000] {standard_task_runner.py:91} INFO - Job 407: Subtask seccond_task
[2024-09-11T01:50:31.256+0000] {task_command.py:426} INFO - Running <TaskInstance: our_first_dag_v4.seccond_task scheduled__2021-12-10T00:00:00+00:00 [running]> on host 0359316e7bd1
[2024-09-11T01:50:31.425+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vohoang' AIRFLOW_CTX_DAG_ID='our_first_dag_v4' AIRFLOW_CTX_TASK_ID='seccond_task' AIRFLOW_CTX_EXECUTION_DATE='2021-12-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-12-10T00:00:00+00:00'
[2024-09-11T01:50:31.426+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-11T01:50:31.449+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-11T01:50:31.451+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "hey, I am task2 and will be running after task 1"']
[2024-09-11T01:50:31.471+0000] {subprocess.py:86} INFO - Output:
[2024-09-11T01:50:31.475+0000] {subprocess.py:93} INFO - hey, I am task2 and will be running after task 1
[2024-09-11T01:50:31.476+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-11T01:50:31.478+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-11T01:50:31.517+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v4, task_id=seccond_task, run_id=scheduled__2021-12-10T00:00:00+00:00, execution_date=20211210T000000, start_date=20240911T015031, end_date=20240911T015031
[2024-09-11T01:50:31.592+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-11T01:50:31.603+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
