[2024-09-11T01:57:44.202+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-11T01:57:44.227+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v4.third_task scheduled__2024-01-28T00:00:00+00:00 [queued]>
[2024-09-11T01:57:44.243+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v4.third_task scheduled__2024-01-28T00:00:00+00:00 [queued]>
[2024-09-11T01:57:44.243+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-09-11T01:57:44.278+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): third_task> on 2024-01-28 00:00:00+00:00
[2024-09-11T01:57:44.290+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=10667) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-11T01:57:44.292+0000] {standard_task_runner.py:63} INFO - Started process 10692 to run task
[2024-09-11T01:57:44.290+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v4', 'third_task', 'scheduled__2024-01-28T00:00:00+00:00', '--job-id', '2817', '--raw', '--subdir', 'DAGS_FOLDER/7. our_first_dag.py', '--cfg-path', '/tmp/tmprv8_5rdj']
[2024-09-11T01:57:44.293+0000] {standard_task_runner.py:91} INFO - Job 2817: Subtask third_task
[2024-09-11T01:57:44.360+0000] {task_command.py:426} INFO - Running <TaskInstance: our_first_dag_v4.third_task scheduled__2024-01-28T00:00:00+00:00 [running]> on host 0359316e7bd1
[2024-09-11T01:57:44.560+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vohoang' AIRFLOW_CTX_DAG_ID='our_first_dag_v4' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-28T00:00:00+00:00'
[2024-09-11T01:57:44.562+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-11T01:57:44.564+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-11T01:57:44.565+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "hey, I am task3 and will be running after task 1"']
[2024-09-11T01:57:44.587+0000] {subprocess.py:86} INFO - Output:
[2024-09-11T01:57:44.590+0000] {subprocess.py:93} INFO - hey, I am task3 and will be running after task 1
[2024-09-11T01:57:44.591+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-11T01:57:44.592+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-11T01:57:44.631+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v4, task_id=third_task, run_id=scheduled__2024-01-28T00:00:00+00:00, execution_date=20240128T000000, start_date=20240911T015744, end_date=20240911T015744
[2024-09-11T01:57:44.668+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-11T01:57:44.691+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-11T01:57:44.699+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
